/* eslint-disable max-len */
import { Injectable } from '@angular/core';
import { Event } from '../../stores/state';


@Injectable({providedIn: 'root'})
export class HotButtonEvents {
  public getHotButtonEvents(): Event[] {
    //7 event cards (GOAL 20)
    const results: Event[] = [
      {
        title:'Hot Button Issue',
        description:'Border Security',
        points: 1,
        imageSrc:'/assets/images/presidents/43-bush.jpg',
        history: 'People want to know your position on Border Security',
        politicanInvolved: '',
        yearInvolved:'2004',
        normalFactDisplay: false,
        statesInvolved: ['CA', 'AZ', 'NM', 'TX'],
        statesInvolved2: ['NV', 'CO', 'FL', 'TX'],
        choiceEvent: true,
        choiceText1: 'More Border Patrol',
        choiceText2: 'Less Border Patrol',
        choicePoints1: 2,
        choicePoints2: -2,
      },
      {
        title:'Hot Button Issue',
        description:'National Healthcare',
        points: 1,
        imageSrc:'/assets/images/presidents/43-bush.jpg',
        history: 'People want to know your position on expanding Medicare',
        politicanInvolved: '',
        yearInvolved:'2004',
        normalFactDisplay: false,
        statesInvolved: ['ID', 'AZ', 'IA', 'OH'],
        statesInvolved2: ['NM', 'IL', 'OR', 'WA'],
        choiceEvent: true,
        choiceText1: 'Expand Medicare',
        choiceText2: 'Reduce Medicare',
        choicePoints1: -3,
        choicePoints2: -3,
      },
      {
        title:'Hot Button Issue',
        description:'Car Company Bailout',
        points: 1,
        imageSrc:'/assets/images/presidents/43-bush.jpg',
        history: 'Car Companies in the midwest are seeking government funds in a "Bail Out" to avoid layoffs',
        politicanInvolved: '',
        yearInvolved:'2004',
        normalFactDisplay: false,
        statesInvolved: ['MI', 'WI', 'PA'],
        statesInvolved2: ['MI', 'WI', 'PA'],
        choiceEvent: true,
        choiceText1: 'Bail out car company',
        choiceText2: 'Don\'t Support Bail Out',
        choicePoints1: 2,
        choicePoints2: -1,
      },
      {
        title:'Hot Button Issue',
        description:'Coal Mining',
        points: 2,
        imageSrc:'/assets/images/presidents/43-bush.jpg',
        history: 'Appalacian Coal Miners want your support of coal mining, while New Englanders are asking you to support Green Energy',
        politicanInvolved: '',
        yearInvolved:'2004',
        normalFactDisplay: false,
        statesInvolved: ['WV', 'KY', 'PA'],
        statesInvolved2: ['NH', 'CT', 'ME'],
        choiceEvent: true,
        choiceText1: 'Support Mining',
        choiceText2: 'Suport Green Energy',
        choicePoints1: 2,
        choicePoints2: 2,
      },
      {
        title:'Hot Button Issue',
        description:'Water Conservation',
        points: 1,
        imageSrc:'/assets/images/presidents/43-bush.jpg',
        history: 'A South Western governor asks if you will spend more on Dams and Water Conservation',
        politicanInvolved: '',
        yearInvolved:'2004',
        normalFactDisplay: false,
        statesInvolved: ['NV', 'UT', 'AZ', 'WY'],
        statesInvolved2: ['NV', 'UT', 'AZ', 'WY'],
        choiceEvent: true,
        choiceText1: 'Spend More',
        choiceText2: 'Keep Spending the Same',
        choicePoints1: 2,
        choicePoints2: -1,
      },
      {
        title:'Hot Button Issue',
        description:'The Mississipi River Has Flooded!',
        points: 2,
        imageSrc:'/assets/images/presidents/43-bush.jpg',
        history: 'A reporter asks whether you support taking money from the defense budget to give aid to effected states.',
        politicanInvolved: '',
        yearInvolved:'2004',
        normalFactDisplay: false,
        statesInvolved: ['MS', 'MO', 'LA', 'AR', 'TN'],
        statesInvolved2: ['MS', 'MO', 'LA', 'AR', 'TN'],
        choiceEvent: true,
        choiceText1: 'Give money to flooded states',
        choiceText2: 'Keep money in defense budget',
        choicePoints1: 2,
        choicePoints2: -4,
      },
      {
        title:'Hot Button Issue',
        description:'A Huricane has Stuck the East Coast!',
        points: 2,
        imageSrc:'/assets/images/presidents/43-bush.jpg',
        history: 'A reporter asks whether you support taking money from the National Parks budget to give aid to effected states.',
        politicanInvolved: '',
        yearInvolved:'2004',
        normalFactDisplay: false,
        statesInvolved: ['NC', 'SC', 'VA', 'MD'],
        statesInvolved2: ['NC', 'SC', 'VA', 'MD'],
        choiceEvent: true,
        choiceText1: 'Give money to flooded states',
        choiceText2: 'Keep money in defense budget',
        choicePoints1: 2,
        choicePoints2: -2,
      },
    ];
    return results;
  }
}
